# Wire up travis
language: python
sudo: false

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.6
          env: TOXENV=py36

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

cache:
  directories:
    - $HOME/.cache/pip
